/*
 * NinjaRMM Webhook (API 2.0)
 *
 * Ninja RMM Public Webhook PSA documentation.
 *
 * The version of the OpenAPI document: 2.0.5-draft
 * Contact: api@ninjarmm.com
 * Generated by: https://openapi-generator.tech
 */

using net.hempux.ninjawebhook.Converters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace net.hempux.ninjawebhook.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class DetailedActivity : IEquatable<DetailedActivity>
    {
        /// <summary>
        /// Activity identifier
        /// </summary>
        /// <value>Activity identifier</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Activity timestamp
        /// </summary>
        /// <value>Activity timestamp</value>
        [DataMember(Name = "activityTime", EmitDefaultValue = false)]
        public long ActivityTime { get; set; }

        /// <summary>
        /// Device identifier
        /// </summary>
        /// <value>Device identifier</value>
        [DataMember(Name = "deviceId", EmitDefaultValue = false)]
        public int DeviceId { get; set; }


        /// <summary>
        /// Severity
        /// </summary>
        /// <value>Severity</value>
        [TypeConverter(typeof(CustomEnumConverter<SeverityEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum SeverityEnum
        {

            /// <summary>
            /// Enum NONEEnum for NONE
            /// </summary>
            [EnumMember(Value = "NONE")]
            NONEEnum = 1,

            /// <summary>
            /// Enum MINOREnum for MINOR
            /// </summary>
            [EnumMember(Value = "MINOR")]
            MINOREnum = 2,

            /// <summary>
            /// Enum MODERATEEnum for MODERATE
            /// </summary>
            [EnumMember(Value = "MODERATE")]
            MODERATEEnum = 3,

            /// <summary>
            /// Enum MAJOREnum for MAJOR
            /// </summary>
            [EnumMember(Value = "MAJOR")]
            MAJOREnum = 4,

            /// <summary>
            /// Enum CRITICALEnum for CRITICAL
            /// </summary>
            [EnumMember(Value = "CRITICAL")]
            CRITICALEnum = 5
        }

        /// <summary>
        /// Severity
        /// </summary>
        /// <value>Severity</value>
        [DataMember(Name = "severity", EmitDefaultValue = false)]
        public SeverityEnum Severity { get; set; }


        /// <summary>
        /// Priority
        /// </summary>
        /// <value>Priority</value>
        [TypeConverter(typeof(CustomEnumConverter<PriorityEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PriorityEnum
        {

            /// <summary>
            /// Enum NONEEnum for NONE
            /// </summary>
            [EnumMember(Value = "NONE")]
            NONEEnum = 1,

            /// <summary>
            /// Enum LOWEnum for LOW
            /// </summary>
            [EnumMember(Value = "LOW")]
            LOWEnum = 2,

            /// <summary>
            /// Enum MEDIUMEnum for MEDIUM
            /// </summary>
            [EnumMember(Value = "MEDIUM")]
            MEDIUMEnum = 3,

            /// <summary>
            /// Enum HIGHEnum for HIGH
            /// </summary>
            [EnumMember(Value = "HIGH")]
            HIGHEnum = 4
        }

        /// <summary>
        /// Priority
        /// </summary>
        /// <value>Priority</value>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public PriorityEnum Priority { get; set; }

        /// <summary>
        /// Activity series UID (job/condition UID)
        /// </summary>
        /// <value>Activity series UID (job/condition UID)</value>
        [DataMember(Name = "seriesUid", EmitDefaultValue = false)]
        public Guid SeriesUid { get; set; }


        /// <summary>
        /// Activity type code
        /// </summary>
        /// <value>Activity type code</value>
        [TypeConverter(typeof(CustomEnumConverter<ActivityTypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ActivityTypeEnum
        {

            /// <summary>
            /// Enum ACTIONSETEnum for ACTIONSET
            /// </summary>
            [EnumMember(Value = "ACTIONSET")]
            ACTIONSETEnum = 1,

            /// <summary>
            /// Enum ACTIONEnum for ACTION
            /// </summary>
            [EnumMember(Value = "ACTION")]
            ACTIONEnum = 2,

            /// <summary>
            /// Enum CONDITIONEnum for CONDITION
            /// </summary>
            [EnumMember(Value = "CONDITION")]
            CONDITIONEnum = 3,

            /// <summary>
            /// Enum CONDITIONACTIONSETEnum for CONDITION_ACTIONSET
            /// </summary>
            [EnumMember(Value = "CONDITION_ACTIONSET")]
            CONDITIONACTIONSETEnum = 4,

            /// <summary>
            /// Enum CONDITIONACTIONEnum for CONDITION_ACTION
            /// </summary>
            [EnumMember(Value = "CONDITION_ACTION")]
            CONDITIONACTIONEnum = 5,

            /// <summary>
            /// Enum ANTIVIRUSEnum for ANTIVIRUS
            /// </summary>
            [EnumMember(Value = "ANTIVIRUS")]
            ANTIVIRUSEnum = 6,

            /// <summary>
            /// Enum PATCHMANAGEMENTEnum for PATCH_MANAGEMENT
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT")]
            PATCHMANAGEMENTEnum = 7,

            /// <summary>
            /// Enum TEAMVIEWEREnum for TEAMVIEWER
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER")]
            TEAMVIEWEREnum = 8,

            /// <summary>
            /// Enum MONITOREnum for MONITOR
            /// </summary>
            [EnumMember(Value = "MONITOR")]
            MONITOREnum = 9,

            /// <summary>
            /// Enum SYSTEMEnum for SYSTEM
            /// </summary>
            [EnumMember(Value = "SYSTEM")]
            SYSTEMEnum = 10,

            /// <summary>
            /// Enum COMMENTEnum for COMMENT
            /// </summary>
            [EnumMember(Value = "COMMENT")]
            COMMENTEnum = 11,

            /// <summary>
            /// Enum SHADOWPROTECTEnum for SHADOWPROTECT
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT")]
            SHADOWPROTECTEnum = 12,

            /// <summary>
            /// Enum IMAGEMANAGEREnum for IMAGEMANAGER
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER")]
            IMAGEMANAGEREnum = 13,

            /// <summary>
            /// Enum HELPREQUESTEnum for HELP_REQUEST
            /// </summary>
            [EnumMember(Value = "HELP_REQUEST")]
            HELPREQUESTEnum = 14,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTEnum for SOFTWARE_PATCH_MANAGEMENT
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT")]
            SOFTWAREPATCHMANAGEMENTEnum = 15,

            /// <summary>
            /// Enum SPLASHTOPEnum for SPLASHTOP
            /// </summary>
            [EnumMember(Value = "SPLASHTOP")]
            SPLASHTOPEnum = 16,

            /// <summary>
            /// Enum CLOUDBERRYEnum for CLOUDBERRY
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY")]
            CLOUDBERRYEnum = 17,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPEnum for CLOUDBERRY_BACKUP
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUP")]
            CLOUDBERRYBACKUPEnum = 18,

            /// <summary>
            /// Enum SCHEDULEDTASKEnum for SCHEDULED_TASK
            /// </summary>
            [EnumMember(Value = "SCHEDULED_TASK")]
            SCHEDULEDTASKEnum = 19,

            /// <summary>
            /// Enum RDPEnum for RDP
            /// </summary>
            [EnumMember(Value = "RDP")]
            RDPEnum = 20,

            /// <summary>
            /// Enum SCRIPTINGEnum for SCRIPTING
            /// </summary>
            [EnumMember(Value = "SCRIPTING")]
            SCRIPTINGEnum = 21,

            /// <summary>
            /// Enum SECURITYEnum for SECURITY
            /// </summary>
            [EnumMember(Value = "SECURITY")]
            SECURITYEnum = 22,

            /// <summary>
            /// Enum REMOTETOOLSEnum for REMOTE_TOOLS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS")]
            REMOTETOOLSEnum = 23,

            /// <summary>
            /// Enum VIRTUALIZATIONEnum for VIRTUALIZATION
            /// </summary>
            [EnumMember(Value = "VIRTUALIZATION")]
            VIRTUALIZATIONEnum = 24,

            /// <summary>
            /// Enum PSAEnum for PSA
            /// </summary>
            [EnumMember(Value = "PSA")]
            PSAEnum = 25
        }

        /// <summary>
        /// Activity type code
        /// </summary>
        /// <value>Activity type code</value>
        [DataMember(Name = "activityType", EmitDefaultValue = false)]
        public ActivityTypeEnum ActivityType { get; set; }


        /// <summary>
        /// Activity status code
        /// </summary>
        /// <value>Activity status code</value>
        [TypeConverter(typeof(CustomEnumConverter<StatusCodeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum StatusCodeEnum
        {

            /// <summary>
            /// Enum STARTREQUESTEDEnum for START_REQUESTED
            /// </summary>
            [EnumMember(Value = "START_REQUESTED")]
            STARTREQUESTEDEnum = 1,

            /// <summary>
            /// Enum STARTEDEnum for STARTED
            /// </summary>
            [EnumMember(Value = "STARTED")]
            STARTEDEnum = 2,

            /// <summary>
            /// Enum INPROCESSEnum for IN_PROCESS
            /// </summary>
            [EnumMember(Value = "IN_PROCESS")]
            INPROCESSEnum = 3,

            /// <summary>
            /// Enum COMPLETEDEnum for COMPLETED
            /// </summary>
            [EnumMember(Value = "COMPLETED")]
            COMPLETEDEnum = 4,

            /// <summary>
            /// Enum CANCELREQUESTEDEnum for CANCEL_REQUESTED
            /// </summary>
            [EnumMember(Value = "CANCEL_REQUESTED")]
            CANCELREQUESTEDEnum = 5,

            /// <summary>
            /// Enum CANCELLEDEnum for CANCELLED
            /// </summary>
            [EnumMember(Value = "CANCELLED")]
            CANCELLEDEnum = 6,

            /// <summary>
            /// Enum TRIGGEREDEnum for TRIGGERED
            /// </summary>
            [EnumMember(Value = "TRIGGERED")]
            TRIGGEREDEnum = 7,

            /// <summary>
            /// Enum RESETEnum for RESET
            /// </summary>
            [EnumMember(Value = "RESET")]
            RESETEnum = 8,

            /// <summary>
            /// Enum ACKNOWLEDGEDEnum for ACKNOWLEDGED
            /// </summary>
            [EnumMember(Value = "ACKNOWLEDGED")]
            ACKNOWLEDGEDEnum = 9,

            /// <summary>
            /// Enum DISABLEDEnum for DISABLED
            /// </summary>
            [EnumMember(Value = "DISABLED")]
            DISABLEDEnum = 10,

            /// <summary>
            /// Enum EVALUATIONFAILUREEnum for EVALUATION_FAILURE
            /// </summary>
            [EnumMember(Value = "EVALUATION_FAILURE")]
            EVALUATIONFAILUREEnum = 11,

            /// <summary>
            /// Enum CLIENTCREATEDEnum for CLIENT_CREATED
            /// </summary>
            [EnumMember(Value = "CLIENT_CREATED")]
            CLIENTCREATEDEnum = 12,

            /// <summary>
            /// Enum CLIENTUPDATEDEnum for CLIENT_UPDATED
            /// </summary>
            [EnumMember(Value = "CLIENT_UPDATED")]
            CLIENTUPDATEDEnum = 13,

            /// <summary>
            /// Enum CLIENTDELETEDEnum for CLIENT_DELETED
            /// </summary>
            [EnumMember(Value = "CLIENT_DELETED")]
            CLIENTDELETEDEnum = 14,

            /// <summary>
            /// Enum POLICYCREATEDEnum for POLICY_CREATED
            /// </summary>
            [EnumMember(Value = "POLICY_CREATED")]
            POLICYCREATEDEnum = 15,

            /// <summary>
            /// Enum POLICYUPDATEDEnum for POLICY_UPDATED
            /// </summary>
            [EnumMember(Value = "POLICY_UPDATED")]
            POLICYUPDATEDEnum = 16,

            /// <summary>
            /// Enum POLICYDELETEDEnum for POLICY_DELETED
            /// </summary>
            [EnumMember(Value = "POLICY_DELETED")]
            POLICYDELETEDEnum = 17,

            /// <summary>
            /// Enum NODECREATEDEnum for NODE_CREATED
            /// </summary>
            [EnumMember(Value = "NODE_CREATED")]
            NODECREATEDEnum = 18,

            /// <summary>
            /// Enum NODEUPDATEDEnum for NODE_UPDATED
            /// </summary>
            [EnumMember(Value = "NODE_UPDATED")]
            NODEUPDATEDEnum = 19,

            /// <summary>
            /// Enum NODEDELETEDEnum for NODE_DELETED
            /// </summary>
            [EnumMember(Value = "NODE_DELETED")]
            NODEDELETEDEnum = 20,

            /// <summary>
            /// Enum LOCATIONCREATEDEnum for LOCATION_CREATED
            /// </summary>
            [EnumMember(Value = "LOCATION_CREATED")]
            LOCATIONCREATEDEnum = 21,

            /// <summary>
            /// Enum LOCATIONUPDATEDEnum for LOCATION_UPDATED
            /// </summary>
            [EnumMember(Value = "LOCATION_UPDATED")]
            LOCATIONUPDATEDEnum = 22,

            /// <summary>
            /// Enum LOCATIONDELETEDEnum for LOCATION_DELETED
            /// </summary>
            [EnumMember(Value = "LOCATION_DELETED")]
            LOCATIONDELETEDEnum = 23,

            /// <summary>
            /// Enum NODEACCESSGRANTEDEnum for NODE_ACCESS_GRANTED
            /// </summary>
            [EnumMember(Value = "NODE_ACCESS_GRANTED")]
            NODEACCESSGRANTEDEnum = 24,

            /// <summary>
            /// Enum NODEACCESSDENIEDEnum for NODE_ACCESS_DENIED
            /// </summary>
            [EnumMember(Value = "NODE_ACCESS_DENIED")]
            NODEACCESSDENIEDEnum = 25,

            /// <summary>
            /// Enum NODEREGISTRATIONREJECTEDEnum for NODE_REGISTRATION_REJECTED
            /// </summary>
            [EnumMember(Value = "NODE_REGISTRATION_REJECTED")]
            NODEREGISTRATIONREJECTEDEnum = 26,

            /// <summary>
            /// Enum APPUSERCREATEDEnum for APP_USER_CREATED
            /// </summary>
            [EnumMember(Value = "APP_USER_CREATED")]
            APPUSERCREATEDEnum = 27,

            /// <summary>
            /// Enum APPUSERUPDATEDEnum for APP_USER_UPDATED
            /// </summary>
            [EnumMember(Value = "APP_USER_UPDATED")]
            APPUSERUPDATEDEnum = 28,

            /// <summary>
            /// Enum APPUSERDELETEDEnum for APP_USER_DELETED
            /// </summary>
            [EnumMember(Value = "APP_USER_DELETED")]
            APPUSERDELETEDEnum = 29,

            /// <summary>
            /// Enum APPUSERLOGGEDINEnum for APP_USER_LOGGED_IN
            /// </summary>
            [EnumMember(Value = "APP_USER_LOGGED_IN")]
            APPUSERLOGGEDINEnum = 30,

            /// <summary>
            /// Enum APPUSERLOGGEDOUTEnum for APP_USER_LOGGED_OUT
            /// </summary>
            [EnumMember(Value = "APP_USER_LOGGED_OUT")]
            APPUSERLOGGEDOUTEnum = 31,

            /// <summary>
            /// Enum APPUSERMFASETUPEnum for APP_USER_MFA_SETUP
            /// </summary>
            [EnumMember(Value = "APP_USER_MFA_SETUP")]
            APPUSERMFASETUPEnum = 32,

            /// <summary>
            /// Enum APPUSERMFADELETEDEnum for APP_USER_MFA_DELETED
            /// </summary>
            [EnumMember(Value = "APP_USER_MFA_DELETED")]
            APPUSERMFADELETEDEnum = 33,

            /// <summary>
            /// Enum ENDUSERCREATEDEnum for END_USER_CREATED
            /// </summary>
            [EnumMember(Value = "END_USER_CREATED")]
            ENDUSERCREATEDEnum = 34,

            /// <summary>
            /// Enum ENDUSERUPDATEDEnum for END_USER_UPDATED
            /// </summary>
            [EnumMember(Value = "END_USER_UPDATED")]
            ENDUSERUPDATEDEnum = 35,

            /// <summary>
            /// Enum ENDUSERDELETEDEnum for END_USER_DELETED
            /// </summary>
            [EnumMember(Value = "END_USER_DELETED")]
            ENDUSERDELETEDEnum = 36,

            /// <summary>
            /// Enum ENDUSERLOGGEDINEnum for END_USER_LOGGED_IN
            /// </summary>
            [EnumMember(Value = "END_USER_LOGGED_IN")]
            ENDUSERLOGGEDINEnum = 37,

            /// <summary>
            /// Enum ENDUSERLOGGEDOUTEnum for END_USER_LOGGED_OUT
            /// </summary>
            [EnumMember(Value = "END_USER_LOGGED_OUT")]
            ENDUSERLOGGEDOUTEnum = 38,

            /// <summary>
            /// Enum ENDUSERMFASETUPEnum for END_USER_MFA_SETUP
            /// </summary>
            [EnumMember(Value = "END_USER_MFA_SETUP")]
            ENDUSERMFASETUPEnum = 39,

            /// <summary>
            /// Enum ENDUSERMFADELETEDEnum for END_USER_MFA_DELETED
            /// </summary>
            [EnumMember(Value = "END_USER_MFA_DELETED")]
            ENDUSERMFADELETEDEnum = 40,

            /// <summary>
            /// Enum TICKETTEMPLATECREATEDEnum for TICKET_TEMPLATE_CREATED
            /// </summary>
            [EnumMember(Value = "TICKET_TEMPLATE_CREATED")]
            TICKETTEMPLATECREATEDEnum = 41,

            /// <summary>
            /// Enum TICKETTEMPLATEUPDATEDEnum for TICKET_TEMPLATE_UPDATED
            /// </summary>
            [EnumMember(Value = "TICKET_TEMPLATE_UPDATED")]
            TICKETTEMPLATEUPDATEDEnum = 42,

            /// <summary>
            /// Enum TICKETTEMPLATEDELETEDEnum for TICKET_TEMPLATE_DELETED
            /// </summary>
            [EnumMember(Value = "TICKET_TEMPLATE_DELETED")]
            TICKETTEMPLATEDELETEDEnum = 43,

            /// <summary>
            /// Enum PSATICKETCREATIONFAILEDEnum for PSA_TICKET_CREATION_FAILED
            /// </summary>
            [EnumMember(Value = "PSA_TICKET_CREATION_FAILED")]
            PSATICKETCREATIONFAILEDEnum = 44,

            /// <summary>
            /// Enum PSATICKETCREATIONSUCCEEDEDEnum for PSA_TICKET_CREATION_SUCCEEDED
            /// </summary>
            [EnumMember(Value = "PSA_TICKET_CREATION_SUCCEEDED")]
            PSATICKETCREATIONSUCCEEDEDEnum = 45,

            /// <summary>
            /// Enum RESETBYPSATICKETCALLBACKEnum for RESET_BY_PSA_TICKET_CALLBACK
            /// </summary>
            [EnumMember(Value = "RESET_BY_PSA_TICKET_CALLBACK")]
            RESETBYPSATICKETCALLBACKEnum = 46,

            /// <summary>
            /// Enum PSATICKETCREATIONTESTEnum for PSA_TICKET_CREATION_TEST
            /// </summary>
            [EnumMember(Value = "PSA_TICKET_CREATION_TEST")]
            PSATICKETCREATIONTESTEnum = 47,

            /// <summary>
            /// Enum PSAENABLEDEnum for PSA_ENABLED
            /// </summary>
            [EnumMember(Value = "PSA_ENABLED")]
            PSAENABLEDEnum = 48,

            /// <summary>
            /// Enum PSADISABLEDEnum for PSA_DISABLED
            /// </summary>
            [EnumMember(Value = "PSA_DISABLED")]
            PSADISABLEDEnum = 49,

            /// <summary>
            /// Enum PSACREDENTIALSFAILEDEnum for PSA_CREDENTIALS_FAILED
            /// </summary>
            [EnumMember(Value = "PSA_CREDENTIALS_FAILED")]
            PSACREDENTIALSFAILEDEnum = 50,

            /// <summary>
            /// Enum CONNECTWISEAGREEMENTSSYNCCOMPLETEDEnum for CONNECTWISE_AGREEMENTS_SYNC_COMPLETED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_AGREEMENTS_SYNC_COMPLETED")]
            CONNECTWISEAGREEMENTSSYNCCOMPLETEDEnum = 51,

            /// <summary>
            /// Enum CONNECTWISEAGREEMENTSSYNCSTARTEDEnum for CONNECTWISE_AGREEMENTS_SYNC_STARTED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_AGREEMENTS_SYNC_STARTED")]
            CONNECTWISEAGREEMENTSSYNCSTARTEDEnum = 52,

            /// <summary>
            /// Enum CONNECTWISENODESYNCCOMPLETEDEnum for CONNECTWISE_NODE_SYNC_COMPLETED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_NODE_SYNC_COMPLETED")]
            CONNECTWISENODESYNCCOMPLETEDEnum = 53,

            /// <summary>
            /// Enum CONNECTWISENODESYNCSTARTEDEnum for CONNECTWISE_NODE_SYNC_STARTED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_NODE_SYNC_STARTED")]
            CONNECTWISENODESYNCSTARTEDEnum = 54,

            /// <summary>
            /// Enum CONNECTWISENODESYNCNODECREATEDEnum for CONNECTWISE_NODE_SYNC_NODE_CREATED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_NODE_SYNC_NODE_CREATED")]
            CONNECTWISENODESYNCNODECREATEDEnum = 55,

            /// <summary>
            /// Enum CONNECTWISENODESYNCNODEUPDATEDEnum for CONNECTWISE_NODE_SYNC_NODE_UPDATED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_NODE_SYNC_NODE_UPDATED")]
            CONNECTWISENODESYNCNODEUPDATEDEnum = 56,

            /// <summary>
            /// Enum CONNECTWISENODESYNCNODEDELETEDEnum for CONNECTWISE_NODE_SYNC_NODE_DELETED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_NODE_SYNC_NODE_DELETED")]
            CONNECTWISENODESYNCNODEDELETEDEnum = 57,

            /// <summary>
            /// Enum CONNECTWISEUPDATEDEnum for CONNECTWISE_UPDATED
            /// </summary>
            [EnumMember(Value = "CONNECTWISE_UPDATED")]
            CONNECTWISEUPDATEDEnum = 58,

            /// <summary>
            /// Enum CREDENTIALCREATEDEnum for CREDENTIAL_CREATED
            /// </summary>
            [EnumMember(Value = "CREDENTIAL_CREATED")]
            CREDENTIALCREATEDEnum = 59,

            /// <summary>
            /// Enum CREDENTIALUPDATEDEnum for CREDENTIAL_UPDATED
            /// </summary>
            [EnumMember(Value = "CREDENTIAL_UPDATED")]
            CREDENTIALUPDATEDEnum = 60,

            /// <summary>
            /// Enum CREDENTIALDELETEDEnum for CREDENTIAL_DELETED
            /// </summary>
            [EnumMember(Value = "CREDENTIAL_DELETED")]
            CREDENTIALDELETEDEnum = 61,

            /// <summary>
            /// Enum REPORTCREATEDEnum for REPORT_CREATED
            /// </summary>
            [EnumMember(Value = "REPORT_CREATED")]
            REPORTCREATEDEnum = 62,

            /// <summary>
            /// Enum REPORTUPDATEDEnum for REPORT_UPDATED
            /// </summary>
            [EnumMember(Value = "REPORT_UPDATED")]
            REPORTUPDATEDEnum = 63,

            /// <summary>
            /// Enum REPORTDELETEDEnum for REPORT_DELETED
            /// </summary>
            [EnumMember(Value = "REPORT_DELETED")]
            REPORTDELETEDEnum = 64,

            /// <summary>
            /// Enum TIMEZONEUPDATEDEnum for TIME_ZONE_UPDATED
            /// </summary>
            [EnumMember(Value = "TIME_ZONE_UPDATED")]
            TIMEZONEUPDATEDEnum = 65,

            /// <summary>
            /// Enum LANGUAGETAGUPDATEDEnum for LANGUAGE_TAG_UPDATED
            /// </summary>
            [EnumMember(Value = "LANGUAGE_TAG_UPDATED")]
            LANGUAGETAGUPDATEDEnum = 66,

            /// <summary>
            /// Enum APPUSERCRITICALACTIONEnum for APP_USER_CRITICAL_ACTION
            /// </summary>
            [EnumMember(Value = "APP_USER_CRITICAL_ACTION")]
            APPUSERCRITICALACTIONEnum = 67,

            /// <summary>
            /// Enum APPUSERAUDITFAILEDLOGINEnum for APP_USER_AUDIT_FAILED_LOGIN
            /// </summary>
            [EnumMember(Value = "APP_USER_AUDIT_FAILED_LOGIN")]
            APPUSERAUDITFAILEDLOGINEnum = 68,

            /// <summary>
            /// Enum ENDUSERAUDITFAILEDLOGINEnum for END_USER_AUDIT_FAILED_LOGIN
            /// </summary>
            [EnumMember(Value = "END_USER_AUDIT_FAILED_LOGIN")]
            ENDUSERAUDITFAILEDLOGINEnum = 69,

            /// <summary>
            /// Enum NODEROLECREATEDEnum for NODE_ROLE_CREATED
            /// </summary>
            [EnumMember(Value = "NODE_ROLE_CREATED")]
            NODEROLECREATEDEnum = 70,

            /// <summary>
            /// Enum NODEROLEUPDATEDEnum for NODE_ROLE_UPDATED
            /// </summary>
            [EnumMember(Value = "NODE_ROLE_UPDATED")]
            NODEROLEUPDATEDEnum = 71,

            /// <summary>
            /// Enum NODEROLEDELETEDEnum for NODE_ROLE_DELETED
            /// </summary>
            [EnumMember(Value = "NODE_ROLE_DELETED")]
            NODEROLEDELETEDEnum = 72,

            /// <summary>
            /// Enum COMMENTEnum for COMMENT
            /// </summary>
            [EnumMember(Value = "COMMENT")]
            COMMENTEnum = 73,

            /// <summary>
            /// Enum VIPREAVINSTALLEDEnum for VIPREAV_INSTALLED
            /// </summary>
            [EnumMember(Value = "VIPREAV_INSTALLED")]
            VIPREAVINSTALLEDEnum = 74,

            /// <summary>
            /// Enum VIPREAVINSTALLFAILEDEnum for VIPREAV_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "VIPREAV_INSTALL_FAILED")]
            VIPREAVINSTALLFAILEDEnum = 75,

            /// <summary>
            /// Enum VIPREAVUNINSTALLEDEnum for VIPREAV_UNINSTALLED
            /// </summary>
            [EnumMember(Value = "VIPREAV_UNINSTALLED")]
            VIPREAVUNINSTALLEDEnum = 76,

            /// <summary>
            /// Enum VIPREAVUNINSTALLFAILEDEnum for VIPREAV_UNINSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "VIPREAV_UNINSTALL_FAILED")]
            VIPREAVUNINSTALLFAILEDEnum = 77,

            /// <summary>
            /// Enum VIPREAVSCANTHREATQUARANTINEDEnum for VIPREAV_SCAN_THREAT_QUARANTINED
            /// </summary>
            [EnumMember(Value = "VIPREAV_SCAN_THREAT_QUARANTINED")]
            VIPREAVSCANTHREATQUARANTINEDEnum = 78,

            /// <summary>
            /// Enum VIPREAVACTIVEPROTECTIONTHREATQUARANTINEDEnum for VIPREAV_ACTIVEPROTECTION_THREAT_QUARANTINED
            /// </summary>
            [EnumMember(Value = "VIPREAV_ACTIVEPROTECTION_THREAT_QUARANTINED")]
            VIPREAVACTIVEPROTECTIONTHREATQUARANTINEDEnum = 79,

            /// <summary>
            /// Enum VIPREAVUSERINITIATEDTHREATQUARANTINEDEnum for VIPREAV_USERINITIATED_THREAT_QUARANTINED
            /// </summary>
            [EnumMember(Value = "VIPREAV_USERINITIATED_THREAT_QUARANTINED")]
            VIPREAVUSERINITIATEDTHREATQUARANTINEDEnum = 80,

            /// <summary>
            /// Enum VIPREAVQUARANTINEDTHREATREMOVEDEnum for VIPREAV_QUARANTINED_THREAT_REMOVED
            /// </summary>
            [EnumMember(Value = "VIPREAV_QUARANTINED_THREAT_REMOVED")]
            VIPREAVQUARANTINEDTHREATREMOVEDEnum = 81,

            /// <summary>
            /// Enum VIPREAVREBOOTREQUIREDEnum for VIPREAV_REBOOT_REQUIRED
            /// </summary>
            [EnumMember(Value = "VIPREAV_REBOOT_REQUIRED")]
            VIPREAVREBOOTREQUIREDEnum = 82,

            /// <summary>
            /// Enum VIPREAVSCANSTARTEDEnum for VIPREAV_SCAN_STARTED
            /// </summary>
            [EnumMember(Value = "VIPREAV_SCAN_STARTED")]
            VIPREAVSCANSTARTEDEnum = 83,

            /// <summary>
            /// Enum VIPREAVSCANCOMPLETEDEnum for VIPREAV_SCAN_COMPLETED
            /// </summary>
            [EnumMember(Value = "VIPREAV_SCAN_COMPLETED")]
            VIPREAVSCANCOMPLETEDEnum = 84,

            /// <summary>
            /// Enum VIPREAVSCANABORTEDEnum for VIPREAV_SCAN_ABORTED
            /// </summary>
            [EnumMember(Value = "VIPREAV_SCAN_ABORTED")]
            VIPREAVSCANABORTEDEnum = 85,

            /// <summary>
            /// Enum VIPREAVSCANFAILEDEnum for VIPREAV_SCAN_FAILED
            /// </summary>
            [EnumMember(Value = "VIPREAV_SCAN_FAILED")]
            VIPREAVSCANFAILEDEnum = 86,

            /// <summary>
            /// Enum VIPREAVSCANPAUSEDEnum for VIPREAV_SCAN_PAUSED
            /// </summary>
            [EnumMember(Value = "VIPREAV_SCAN_PAUSED")]
            VIPREAVSCANPAUSEDEnum = 87,

            /// <summary>
            /// Enum VIPREAVDISABLEDEnum for VIPREAV_DISABLED
            /// </summary>
            [EnumMember(Value = "VIPREAV_DISABLED")]
            VIPREAVDISABLEDEnum = 88,

            /// <summary>
            /// Enum WEBROOTCOMMANDSUBMITTEDEnum for WEBROOT_COMMAND_SUBMITTED
            /// </summary>
            [EnumMember(Value = "WEBROOT_COMMAND_SUBMITTED")]
            WEBROOTCOMMANDSUBMITTEDEnum = 89,

            /// <summary>
            /// Enum WEBROOTTHREATDETECTEDEnum for WEBROOT_THREAT_DETECTED
            /// </summary>
            [EnumMember(Value = "WEBROOT_THREAT_DETECTED")]
            WEBROOTTHREATDETECTEDEnum = 90,

            /// <summary>
            /// Enum WEBROOTINSTALLFAILEDEnum for WEBROOT_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "WEBROOT_INSTALL_FAILED")]
            WEBROOTINSTALLFAILEDEnum = 91,

            /// <summary>
            /// Enum BITDEFENDERSCANSTARTEDEnum for BITDEFENDER_SCAN_STARTED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_SCAN_STARTED")]
            BITDEFENDERSCANSTARTEDEnum = 92,

            /// <summary>
            /// Enum BITDEFENDERSCANCOMPLETEDEnum for BITDEFENDER_SCAN_COMPLETED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_SCAN_COMPLETED")]
            BITDEFENDERSCANCOMPLETEDEnum = 93,

            /// <summary>
            /// Enum BITDEFENDERTHREATDELETEFROMQUARANTINEEnum for BITDEFENDER_THREAT_DELETE_FROM_QUARANTINE
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_THREAT_DELETE_FROM_QUARANTINE")]
            BITDEFENDERTHREATDELETEFROMQUARANTINEEnum = 94,

            /// <summary>
            /// Enum BITDEFENDERTHREATRESTOREFROMQUARANTINEEnum for BITDEFENDER_THREAT_RESTORE_FROM_QUARANTINE
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_THREAT_RESTORE_FROM_QUARANTINE")]
            BITDEFENDERTHREATRESTOREFROMQUARANTINEEnum = 95,

            /// <summary>
            /// Enum BITDEFENDERSCANFAILEDEnum for BITDEFENDER_SCAN_FAILED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_SCAN_FAILED")]
            BITDEFENDERSCANFAILEDEnum = 96,

            /// <summary>
            /// Enum BITDEFENDERTHREATDELETEFROMQUARANTINEFAILEDEnum for BITDEFENDER_THREAT_DELETE_FROM_QUARANTINE_FAILED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_THREAT_DELETE_FROM_QUARANTINE_FAILED")]
            BITDEFENDERTHREATDELETEFROMQUARANTINEFAILEDEnum = 97,

            /// <summary>
            /// Enum BITDEFENDERTHREATRESTOREFROMQUARANTINEFAILEDEnum for BITDEFENDER_THREAT_RESTORE_FROM_QUARANTINE_FAILED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_THREAT_RESTORE_FROM_QUARANTINE_FAILED")]
            BITDEFENDERTHREATRESTOREFROMQUARANTINEFAILEDEnum = 98,

            /// <summary>
            /// Enum BITDEFENDERDOWNLOADSTARTEDEnum for BITDEFENDER_DOWNLOAD_STARTED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_DOWNLOAD_STARTED")]
            BITDEFENDERDOWNLOADSTARTEDEnum = 99,

            /// <summary>
            /// Enum BITDEFENDERDOWNLOADSUCCEEDEDEnum for BITDEFENDER_DOWNLOAD_SUCCEEDED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_DOWNLOAD_SUCCEEDED")]
            BITDEFENDERDOWNLOADSUCCEEDEDEnum = 100,

            /// <summary>
            /// Enum BITDEFENDERDOWNLOADFAILEDEnum for BITDEFENDER_DOWNLOAD_FAILED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_DOWNLOAD_FAILED")]
            BITDEFENDERDOWNLOADFAILEDEnum = 101,

            /// <summary>
            /// Enum BITDEFENDERINSTALLATIONSTARTEDEnum for BITDEFENDER_INSTALLATION_STARTED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_INSTALLATION_STARTED")]
            BITDEFENDERINSTALLATIONSTARTEDEnum = 102,

            /// <summary>
            /// Enum BITDEFENDERINSTALLATIONSUCCEEDEDEnum for BITDEFENDER_INSTALLATION_SUCCEEDED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_INSTALLATION_SUCCEEDED")]
            BITDEFENDERINSTALLATIONSUCCEEDEDEnum = 103,

            /// <summary>
            /// Enum BITDEFENDERINSTALLATIONFAILEDEnum for BITDEFENDER_INSTALLATION_FAILED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_INSTALLATION_FAILED")]
            BITDEFENDERINSTALLATIONFAILEDEnum = 104,

            /// <summary>
            /// Enum BITDEFENDERUNINSTALLATIONSTARTEDEnum for BITDEFENDER_UNINSTALLATION_STARTED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_UNINSTALLATION_STARTED")]
            BITDEFENDERUNINSTALLATIONSTARTEDEnum = 105,

            /// <summary>
            /// Enum BITDEFENDERUNINSTALLATIONSUCCEEDEDEnum for BITDEFENDER_UNINSTALLATION_SUCCEEDED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_UNINSTALLATION_SUCCEEDED")]
            BITDEFENDERUNINSTALLATIONSUCCEEDEDEnum = 106,

            /// <summary>
            /// Enum BITDEFENDERUNINSTALLATIONFAILEDEnum for BITDEFENDER_UNINSTALLATION_FAILED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_UNINSTALLATION_FAILED")]
            BITDEFENDERUNINSTALLATIONFAILEDEnum = 107,

            /// <summary>
            /// Enum BITDEFENDERUNPACKINGFAILEDEnum for BITDEFENDER_UNPACKING_FAILED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_UNPACKING_FAILED")]
            BITDEFENDERUNPACKINGFAILEDEnum = 108,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATIGNOREDEnum for BDAS_BITDEFENDER_THREAT_IGNORED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_IGNORED")]
            BDASBITDEFENDERTHREATIGNOREDEnum = 109,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATPRESENTEnum for BDAS_BITDEFENDER_THREAT_PRESENT
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_PRESENT")]
            BDASBITDEFENDERTHREATPRESENTEnum = 110,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATDELETEDEnum for BDAS_BITDEFENDER_THREAT_DELETED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_DELETED")]
            BDASBITDEFENDERTHREATDELETEDEnum = 111,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATBLOCKEDEnum for BDAS_BITDEFENDER_THREAT_BLOCKED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_BLOCKED")]
            BDASBITDEFENDERTHREATBLOCKEDEnum = 112,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATQUARANTINEDEnum for BDAS_BITDEFENDER_THREAT_QUARANTINED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_QUARANTINED")]
            BDASBITDEFENDERTHREATQUARANTINEDEnum = 113,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATCLEANEDEnum for BDAS_BITDEFENDER_THREAT_CLEANED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_CLEANED")]
            BDASBITDEFENDERTHREATCLEANEDEnum = 114,

            /// <summary>
            /// Enum BDASBITDEFENDERPURGEQUARANTINEFAILEDEnum for BDAS_BITDEFENDER_PURGE_QUARANTINE_FAILED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_PURGE_QUARANTINE_FAILED")]
            BDASBITDEFENDERPURGEQUARANTINEFAILEDEnum = 115,

            /// <summary>
            /// Enum BDASBITDEFENDERPURGEQUARANTINESUCCESSEnum for BDAS_BITDEFENDER_PURGE_QUARANTINE_SUCCESS
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_PURGE_QUARANTINE_SUCCESS")]
            BDASBITDEFENDERPURGEQUARANTINESUCCESSEnum = 116,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATQUARANTINERESTOREDEnum for BDAS_BITDEFENDER_THREAT_QUARANTINE_RESTORED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_QUARANTINE_RESTORED")]
            BDASBITDEFENDERTHREATQUARANTINERESTOREDEnum = 117,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATQUARANTINERESTOREDCUSTOMPATHEnum for BDAS_BITDEFENDER_THREAT_QUARANTINE_RESTORED_CUSTOMPATH
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_QUARANTINE_RESTORED_CUSTOMPATH")]
            BDASBITDEFENDERTHREATQUARANTINERESTOREDCUSTOMPATHEnum = 118,

            /// <summary>
            /// Enum BDASBITDEFENDERTHREATQUARANTINEDELETEDEnum for BDAS_BITDEFENDER_THREAT_QUARANTINE_DELETED
            /// </summary>
            [EnumMember(Value = "BDAS_BITDEFENDER_THREAT_QUARANTINE_DELETED")]
            BDASBITDEFENDERTHREATQUARANTINEDELETEDEnum = 119,

            /// <summary>
            /// Enum BITDEFENDERRETRYINSTALLCOMPLETEDEnum for BITDEFENDER_RETRY_INSTALL_COMPLETED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_RETRY_INSTALL_COMPLETED")]
            BITDEFENDERRETRYINSTALLCOMPLETEDEnum = 120,

            /// <summary>
            /// Enum BITDEFENDERDISABLEDEnum for BITDEFENDER_DISABLED
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_DISABLED")]
            BITDEFENDERDISABLEDEnum = 121,

            /// <summary>
            /// Enum BITDEFENDEREXISTINGPRODUCTUNINSTALLEnum for BITDEFENDER_EXISTING_PRODUCT_UNINSTALL
            /// </summary>
            [EnumMember(Value = "BITDEFENDER_EXISTING_PRODUCT_UNINSTALL")]
            BITDEFENDEREXISTINGPRODUCTUNINSTALLEnum = 122,

            /// <summary>
            /// Enum COMPETITOREXISTINGPRODUCTUNINSTALLEnum for COMPETITOR_EXISTING_PRODUCT_UNINSTALL
            /// </summary>
            [EnumMember(Value = "COMPETITOR_EXISTING_PRODUCT_UNINSTALL")]
            COMPETITOREXISTINGPRODUCTUNINSTALLEnum = 123,

            /// <summary>
            /// Enum SCHEDULEINSTALLOPTIONCHANGEDEnum for SCHEDULE_INSTALL_OPTION_CHANGED
            /// </summary>
            [EnumMember(Value = "SCHEDULE_INSTALL_OPTION_CHANGED")]
            SCHEDULEINSTALLOPTIONCHANGEDEnum = 124,

            /// <summary>
            /// Enum PATCHMANAGEMENTSCANSTARTEDEnum for PATCH_MANAGEMENT_SCAN_STARTED
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_SCAN_STARTED")]
            PATCHMANAGEMENTSCANSTARTEDEnum = 125,

            /// <summary>
            /// Enum PATCHMANAGEMENTSCANCOMPLETEDEnum for PATCH_MANAGEMENT_SCAN_COMPLETED
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_SCAN_COMPLETED")]
            PATCHMANAGEMENTSCANCOMPLETEDEnum = 126,

            /// <summary>
            /// Enum PATCHMANAGEMENTAPPLYPATCHSTARTEDEnum for PATCH_MANAGEMENT_APPLY_PATCH_STARTED
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_APPLY_PATCH_STARTED")]
            PATCHMANAGEMENTAPPLYPATCHSTARTEDEnum = 127,

            /// <summary>
            /// Enum PATCHMANAGEMENTAPPLYPATCHCOMPLETEDEnum for PATCH_MANAGEMENT_APPLY_PATCH_COMPLETED
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_APPLY_PATCH_COMPLETED")]
            PATCHMANAGEMENTAPPLYPATCHCOMPLETEDEnum = 128,

            /// <summary>
            /// Enum PATCHMANAGEMENTINSTALLEDEnum for PATCH_MANAGEMENT_INSTALLED
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_INSTALLED")]
            PATCHMANAGEMENTINSTALLEDEnum = 129,

            /// <summary>
            /// Enum PATCHMANAGEMENTINSTALLFAILEDEnum for PATCH_MANAGEMENT_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_INSTALL_FAILED")]
            PATCHMANAGEMENTINSTALLFAILEDEnum = 130,

            /// <summary>
            /// Enum PATCHMANAGEMENTMESSAGEEnum for PATCH_MANAGEMENT_MESSAGE
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_MESSAGE")]
            PATCHMANAGEMENTMESSAGEEnum = 131,

            /// <summary>
            /// Enum PATCHMANAGEMENTFAILUREEnum for PATCH_MANAGEMENT_FAILURE
            /// </summary>
            [EnumMember(Value = "PATCH_MANAGEMENT_FAILURE")]
            PATCHMANAGEMENTFAILUREEnum = 132,

            /// <summary>
            /// Enum TEAMVIEWERINSTALLEDEnum for TEAMVIEWER_INSTALLED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_INSTALLED")]
            TEAMVIEWERINSTALLEDEnum = 133,

            /// <summary>
            /// Enum TEAMVIEWERINSTALLFAILEDEnum for TEAMVIEWER_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_INSTALL_FAILED")]
            TEAMVIEWERINSTALLFAILEDEnum = 134,

            /// <summary>
            /// Enum TEAMVIEWERUNINSTALLEDEnum for TEAMVIEWER_UNINSTALLED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_UNINSTALLED")]
            TEAMVIEWERUNINSTALLEDEnum = 135,

            /// <summary>
            /// Enum TEAMVIEWERUNINSTALLFAILEDEnum for TEAMVIEWER_UNINSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_UNINSTALL_FAILED")]
            TEAMVIEWERUNINSTALLFAILEDEnum = 136,

            /// <summary>
            /// Enum TEAMVIEWERCONNECTIONESTABLISHEDEnum for TEAMVIEWER_CONNECTION_ESTABLISHED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_CONNECTION_ESTABLISHED")]
            TEAMVIEWERCONNECTIONESTABLISHEDEnum = 137,

            /// <summary>
            /// Enum TEAMVIEWERCONNECTIONTERMINATEDEnum for TEAMVIEWER_CONNECTION_TERMINATED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_CONNECTION_TERMINATED")]
            TEAMVIEWERCONNECTIONTERMINATEDEnum = 138,

            /// <summary>
            /// Enum TEAMVIEWERPERMANENTPASSWORDCHANGEDEnum for TEAMVIEWER_PERMANENT_PASSWORD_CHANGED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_PERMANENT_PASSWORD_CHANGED")]
            TEAMVIEWERPERMANENTPASSWORDCHANGEDEnum = 139,

            /// <summary>
            /// Enum TEAMVIEWERACCOUNTNAMEADDEDEnum for TEAMVIEWER_ACCOUNTNAME_ADDED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_ACCOUNTNAME_ADDED")]
            TEAMVIEWERACCOUNTNAMEADDEDEnum = 140,

            /// <summary>
            /// Enum TEAMVIEWERACCOUNTNAMECHANGEDEnum for TEAMVIEWER_ACCOUNTNAME_CHANGED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_ACCOUNTNAME_CHANGED")]
            TEAMVIEWERACCOUNTNAMECHANGEDEnum = 141,

            /// <summary>
            /// Enum TEAMVIEWERACCOUNTNAMEREMOVEDEnum for TEAMVIEWER_ACCOUNTNAME_REMOVED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_ACCOUNTNAME_REMOVED")]
            TEAMVIEWERACCOUNTNAMEREMOVEDEnum = 142,

            /// <summary>
            /// Enum TEAMVIEWERCONNECTIONCANCELLEDEnum for TEAMVIEWER_CONNECTION_CANCELLED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_CONNECTION_CANCELLED")]
            TEAMVIEWERCONNECTIONCANCELLEDEnum = 143,

            /// <summary>
            /// Enum TEAMVIEWERCONFIGCHANGEDEnum for TEAMVIEWER_CONFIG_CHANGED
            /// </summary>
            [EnumMember(Value = "TEAMVIEWER_CONFIG_CHANGED")]
            TEAMVIEWERCONFIGCHANGEDEnum = 144,

            /// <summary>
            /// Enum SPLASHTOPCONNECTIONINITIATEDEnum for SPLASHTOP_CONNECTION_INITIATED
            /// </summary>
            [EnumMember(Value = "SPLASHTOP_CONNECTION_INITIATED")]
            SPLASHTOPCONNECTIONINITIATEDEnum = 145,

            /// <summary>
            /// Enum SPLASHTOPCONNECTIONESTABLISHEDEnum for SPLASHTOP_CONNECTION_ESTABLISHED
            /// </summary>
            [EnumMember(Value = "SPLASHTOP_CONNECTION_ESTABLISHED")]
            SPLASHTOPCONNECTIONESTABLISHEDEnum = 146,

            /// <summary>
            /// Enum SPLASHTOPCONNECTIONTERMINATEDEnum for SPLASHTOP_CONNECTION_TERMINATED
            /// </summary>
            [EnumMember(Value = "SPLASHTOP_CONNECTION_TERMINATED")]
            SPLASHTOPCONNECTIONTERMINATEDEnum = 147,

            /// <summary>
            /// Enum ADAPTERADDEDEnum for ADAPTER_ADDED
            /// </summary>
            [EnumMember(Value = "ADAPTER_ADDED")]
            ADAPTERADDEDEnum = 148,

            /// <summary>
            /// Enum ADAPTERREMOVEDEnum for ADAPTER_REMOVED
            /// </summary>
            [EnumMember(Value = "ADAPTER_REMOVED")]
            ADAPTERREMOVEDEnum = 149,

            /// <summary>
            /// Enum ADAPTERCONFIGCHANGEDEnum for ADAPTER_CONFIG_CHANGED
            /// </summary>
            [EnumMember(Value = "ADAPTER_CONFIG_CHANGED")]
            ADAPTERCONFIGCHANGEDEnum = 150,

            /// <summary>
            /// Enum ADAPTERSTATUSCHANGEDEnum for ADAPTER_STATUS_CHANGED
            /// </summary>
            [EnumMember(Value = "ADAPTER_STATUS_CHANGED")]
            ADAPTERSTATUSCHANGEDEnum = 151,

            /// <summary>
            /// Enum CPUADDEDEnum for CPU_ADDED
            /// </summary>
            [EnumMember(Value = "CPU_ADDED")]
            CPUADDEDEnum = 152,

            /// <summary>
            /// Enum CPUREMOVEDEnum for CPU_REMOVED
            /// </summary>
            [EnumMember(Value = "CPU_REMOVED")]
            CPUREMOVEDEnum = 153,

            /// <summary>
            /// Enum MEMORYADDEDEnum for MEMORY_ADDED
            /// </summary>
            [EnumMember(Value = "MEMORY_ADDED")]
            MEMORYADDEDEnum = 154,

            /// <summary>
            /// Enum MEMORYREMOVEDEnum for MEMORY_REMOVED
            /// </summary>
            [EnumMember(Value = "MEMORY_REMOVED")]
            MEMORYREMOVEDEnum = 155,

            /// <summary>
            /// Enum DISKDRIVEADDEDEnum for DISK_DRIVE_ADDED
            /// </summary>
            [EnumMember(Value = "DISK_DRIVE_ADDED")]
            DISKDRIVEADDEDEnum = 156,

            /// <summary>
            /// Enum DISKDRIVEREMOVEDEnum for DISK_DRIVE_REMOVED
            /// </summary>
            [EnumMember(Value = "DISK_DRIVE_REMOVED")]
            DISKDRIVEREMOVEDEnum = 157,

            /// <summary>
            /// Enum USERLOGGEDINEnum for USER_LOGGED_IN
            /// </summary>
            [EnumMember(Value = "USER_LOGGED_IN")]
            USERLOGGEDINEnum = 158,

            /// <summary>
            /// Enum USERLOGGEDOUTEnum for USER_LOGGED_OUT
            /// </summary>
            [EnumMember(Value = "USER_LOGGED_OUT")]
            USERLOGGEDOUTEnum = 159,

            /// <summary>
            /// Enum PORTOPENEDEnum for PORT_OPENED
            /// </summary>
            [EnumMember(Value = "PORT_OPENED")]
            PORTOPENEDEnum = 160,

            /// <summary>
            /// Enum PORTCLOSEDEnum for PORT_CLOSED
            /// </summary>
            [EnumMember(Value = "PORT_CLOSED")]
            PORTCLOSEDEnum = 161,

            /// <summary>
            /// Enum WINDOWSSERVICESTARTEDEnum for WINDOWS_SERVICE_STARTED
            /// </summary>
            [EnumMember(Value = "WINDOWS_SERVICE_STARTED")]
            WINDOWSSERVICESTARTEDEnum = 162,

            /// <summary>
            /// Enum WINDOWSSERVICESTOPPEDEnum for WINDOWS_SERVICE_STOPPED
            /// </summary>
            [EnumMember(Value = "WINDOWS_SERVICE_STOPPED")]
            WINDOWSSERVICESTOPPEDEnum = 163,

            /// <summary>
            /// Enum MACDAEMONSTARTEDEnum for MAC_DAEMON_STARTED
            /// </summary>
            [EnumMember(Value = "MAC_DAEMON_STARTED")]
            MACDAEMONSTARTEDEnum = 164,

            /// <summary>
            /// Enum MACDAEMONSTOPPEDEnum for MAC_DAEMON_STOPPED
            /// </summary>
            [EnumMember(Value = "MAC_DAEMON_STOPPED")]
            MACDAEMONSTOPPEDEnum = 165,

            /// <summary>
            /// Enum USERACCOUNTADDEDEnum for USER_ACCOUNT_ADDED
            /// </summary>
            [EnumMember(Value = "USER_ACCOUNT_ADDED")]
            USERACCOUNTADDEDEnum = 166,

            /// <summary>
            /// Enum USERACCOUNTREMOVEDEnum for USER_ACCOUNT_REMOVED
            /// </summary>
            [EnumMember(Value = "USER_ACCOUNT_REMOVED")]
            USERACCOUNTREMOVEDEnum = 167,

            /// <summary>
            /// Enum PROCESSSTARTEDEnum for PROCESS_STARTED
            /// </summary>
            [EnumMember(Value = "PROCESS_STARTED")]
            PROCESSSTARTEDEnum = 168,

            /// <summary>
            /// Enum PROCESSSTOPPEDEnum for PROCESS_STOPPED
            /// </summary>
            [EnumMember(Value = "PROCESS_STOPPED")]
            PROCESSSTOPPEDEnum = 169,

            /// <summary>
            /// Enum SYSTEMREBOOTEDEnum for SYSTEM_REBOOTED
            /// </summary>
            [EnumMember(Value = "SYSTEM_REBOOTED")]
            SYSTEMREBOOTEDEnum = 170,

            /// <summary>
            /// Enum SOFTWAREADDEDEnum for SOFTWARE_ADDED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_ADDED")]
            SOFTWAREADDEDEnum = 171,

            /// <summary>
            /// Enum SOFTWAREREMOVEDEnum for SOFTWARE_REMOVED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_REMOVED")]
            SOFTWAREREMOVEDEnum = 172,

            /// <summary>
            /// Enum DISKPARTITIONADDEDEnum for DISK_PARTITION_ADDED
            /// </summary>
            [EnumMember(Value = "DISK_PARTITION_ADDED")]
            DISKPARTITIONADDEDEnum = 173,

            /// <summary>
            /// Enum DISKPARTITIONREMOVEDEnum for DISK_PARTITION_REMOVED
            /// </summary>
            [EnumMember(Value = "DISK_PARTITION_REMOVED")]
            DISKPARTITIONREMOVEDEnum = 174,

            /// <summary>
            /// Enum DISKVOLUMEADDEDEnum for DISK_VOLUME_ADDED
            /// </summary>
            [EnumMember(Value = "DISK_VOLUME_ADDED")]
            DISKVOLUMEADDEDEnum = 175,

            /// <summary>
            /// Enum DISKVOLUMEREMOVEDEnum for DISK_VOLUME_REMOVED
            /// </summary>
            [EnumMember(Value = "DISK_VOLUME_REMOVED")]
            DISKVOLUMEREMOVEDEnum = 176,

            /// <summary>
            /// Enum CREDENTIALSCHANGEDEnum for CREDENTIALS_CHANGED
            /// </summary>
            [EnumMember(Value = "CREDENTIALS_CHANGED")]
            CREDENTIALSCHANGEDEnum = 177,

            /// <summary>
            /// Enum RAIDCONTROLLERADDEDEnum for RAID_CONTROLLER_ADDED
            /// </summary>
            [EnumMember(Value = "RAID_CONTROLLER_ADDED")]
            RAIDCONTROLLERADDEDEnum = 178,

            /// <summary>
            /// Enum RAIDCONTROLLERREMOVEDEnum for RAID_CONTROLLER_REMOVED
            /// </summary>
            [EnumMember(Value = "RAID_CONTROLLER_REMOVED")]
            RAIDCONTROLLERREMOVEDEnum = 179,

            /// <summary>
            /// Enum RAIDPHYSICALDRIVEADDEDEnum for RAID_PHYSICAL_DRIVE_ADDED
            /// </summary>
            [EnumMember(Value = "RAID_PHYSICAL_DRIVE_ADDED")]
            RAIDPHYSICALDRIVEADDEDEnum = 180,

            /// <summary>
            /// Enum RAIDPHYSICALDRIVEREMOVEDEnum for RAID_PHYSICAL_DRIVE_REMOVED
            /// </summary>
            [EnumMember(Value = "RAID_PHYSICAL_DRIVE_REMOVED")]
            RAIDPHYSICALDRIVEREMOVEDEnum = 181,

            /// <summary>
            /// Enum RAIDLOGICALDISKADDEDEnum for RAID_LOGICAL_DISK_ADDED
            /// </summary>
            [EnumMember(Value = "RAID_LOGICAL_DISK_ADDED")]
            RAIDLOGICALDISKADDEDEnum = 182,

            /// <summary>
            /// Enum RAIDLOGICALDISKREMOVEDEnum for RAID_LOGICAL_DISK_REMOVED
            /// </summary>
            [EnumMember(Value = "RAID_LOGICAL_DISK_REMOVED")]
            RAIDLOGICALDISKREMOVEDEnum = 183,

            /// <summary>
            /// Enum SERVERMESSAGEEnum for SERVER_MESSAGE
            /// </summary>
            [EnumMember(Value = "SERVER_MESSAGE")]
            SERVERMESSAGEEnum = 184,

            /// <summary>
            /// Enum AGENTMESSAGEEnum for AGENT_MESSAGE
            /// </summary>
            [EnumMember(Value = "AGENT_MESSAGE")]
            AGENTMESSAGEEnum = 185,

            /// <summary>
            /// Enum WEBAPPMESSAGEEnum for WEBAPP_MESSAGE
            /// </summary>
            [EnumMember(Value = "WEBAPP_MESSAGE")]
            WEBAPPMESSAGEEnum = 186,

            /// <summary>
            /// Enum SHADOWPROTECTINSTALLEDEnum for SHADOWPROTECT_INSTALLED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_INSTALLED")]
            SHADOWPROTECTINSTALLEDEnum = 187,

            /// <summary>
            /// Enum SHADOWPROTECTINSTALLFAILEDEnum for SHADOWPROTECT_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_INSTALL_FAILED")]
            SHADOWPROTECTINSTALLFAILEDEnum = 188,

            /// <summary>
            /// Enum SHADOWPROTECTUNINSTALLEDEnum for SHADOWPROTECT_UNINSTALLED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_UNINSTALLED")]
            SHADOWPROTECTUNINSTALLEDEnum = 189,

            /// <summary>
            /// Enum SHADOWPROTECTUNINSTALLFAILEDEnum for SHADOWPROTECT_UNINSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_UNINSTALL_FAILED")]
            SHADOWPROTECTUNINSTALLFAILEDEnum = 190,

            /// <summary>
            /// Enum SHADOWPROTECTBACKUPJOBFAILEDEnum for SHADOWPROTECT_BACKUPJOB_FAILED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_BACKUPJOB_FAILED")]
            SHADOWPROTECTBACKUPJOBFAILEDEnum = 191,

            /// <summary>
            /// Enum SHADOWPROTECTBACKUPJOBABORTEDEnum for SHADOWPROTECT_BACKUPJOB_ABORTED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_BACKUPJOB_ABORTED")]
            SHADOWPROTECTBACKUPJOBABORTEDEnum = 192,

            /// <summary>
            /// Enum SHADOWPROTECTLICENSEPROVISIONEDEnum for SHADOWPROTECT_LICENSE_PROVISIONED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_LICENSE_PROVISIONED")]
            SHADOWPROTECTLICENSEPROVISIONEDEnum = 193,

            /// <summary>
            /// Enum SHADOWPROTECTLICENSEPROVISIONFAILEDEnum for SHADOWPROTECT_LICENSE_PROVISION_FAILED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_LICENSE_PROVISION_FAILED")]
            SHADOWPROTECTLICENSEPROVISIONFAILEDEnum = 194,

            /// <summary>
            /// Enum SHADOWPROTECTLICENSEACTIVATEDEnum for SHADOWPROTECT_LICENSE_ACTIVATED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_LICENSE_ACTIVATED")]
            SHADOWPROTECTLICENSEACTIVATEDEnum = 195,

            /// <summary>
            /// Enum SHADOWPROTECTLICENSEACTIVATIONFAILEDEnum for SHADOWPROTECT_LICENSE_ACTIVATION_FAILED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_LICENSE_ACTIVATION_FAILED")]
            SHADOWPROTECTLICENSEACTIVATIONFAILEDEnum = 196,

            /// <summary>
            /// Enum SHADOWPROTECTLICENSEDEACTIVATEDEnum for SHADOWPROTECT_LICENSE_DEACTIVATED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_LICENSE_DEACTIVATED")]
            SHADOWPROTECTLICENSEDEACTIVATEDEnum = 197,

            /// <summary>
            /// Enum SHADOWPROTECTLICENSEDEACTIVATIONFAILEDEnum for SHADOWPROTECT_LICENSE_DEACTIVATION_FAILED
            /// </summary>
            [EnumMember(Value = "SHADOWPROTECT_LICENSE_DEACTIVATION_FAILED")]
            SHADOWPROTECTLICENSEDEACTIVATIONFAILEDEnum = 198,

            /// <summary>
            /// Enum IMAGEMANAGERINSTALLEDEnum for IMAGEMANAGER_INSTALLED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_INSTALLED")]
            IMAGEMANAGERINSTALLEDEnum = 199,

            /// <summary>
            /// Enum IMAGEMANAGERINSTALLFAILEDEnum for IMAGEMANAGER_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_INSTALL_FAILED")]
            IMAGEMANAGERINSTALLFAILEDEnum = 200,

            /// <summary>
            /// Enum IMAGEMANAGERUNINSTALLEDEnum for IMAGEMANAGER_UNINSTALLED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_UNINSTALLED")]
            IMAGEMANAGERUNINSTALLEDEnum = 201,

            /// <summary>
            /// Enum IMAGEMANAGERUNINSTALLFAILEDEnum for IMAGEMANAGER_UNINSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_UNINSTALL_FAILED")]
            IMAGEMANAGERUNINSTALLFAILEDEnum = 202,

            /// <summary>
            /// Enum IMAGEMANAGERLICENSEPROVISIONEDEnum for IMAGEMANAGER_LICENSE_PROVISIONED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_LICENSE_PROVISIONED")]
            IMAGEMANAGERLICENSEPROVISIONEDEnum = 203,

            /// <summary>
            /// Enum IMAGEMANAGERLICENSEPROVISIONFAILEDEnum for IMAGEMANAGER_LICENSE_PROVISION_FAILED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_LICENSE_PROVISION_FAILED")]
            IMAGEMANAGERLICENSEPROVISIONFAILEDEnum = 204,

            /// <summary>
            /// Enum IMAGEMANAGERLICENSEACTIVATEDEnum for IMAGEMANAGER_LICENSE_ACTIVATED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_LICENSE_ACTIVATED")]
            IMAGEMANAGERLICENSEACTIVATEDEnum = 205,

            /// <summary>
            /// Enum IMAGEMANAGERLICENSEACTIVATIONFAILEDEnum for IMAGEMANAGER_LICENSE_ACTIVATION_FAILED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_LICENSE_ACTIVATION_FAILED")]
            IMAGEMANAGERLICENSEACTIVATIONFAILEDEnum = 206,

            /// <summary>
            /// Enum IMAGEMANAGERLICENSEDEACTIVATEDEnum for IMAGEMANAGER_LICENSE_DEACTIVATED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_LICENSE_DEACTIVATED")]
            IMAGEMANAGERLICENSEDEACTIVATEDEnum = 207,

            /// <summary>
            /// Enum IMAGEMANAGERLICENSEDEACTIVATIONFAILEDEnum for IMAGEMANAGER_LICENSE_DEACTIVATION_FAILED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_LICENSE_DEACTIVATION_FAILED")]
            IMAGEMANAGERLICENSEDEACTIVATIONFAILEDEnum = 208,

            /// <summary>
            /// Enum IMAGEMANAGERCONSOLIDATIONFAILEDEnum for IMAGEMANAGER_CONSOLIDATION_FAILED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_CONSOLIDATION_FAILED")]
            IMAGEMANAGERCONSOLIDATIONFAILEDEnum = 209,

            /// <summary>
            /// Enum IMAGEMANAGERVERIFICATIONFAILEDEnum for IMAGEMANAGER_VERIFICATION_FAILED
            /// </summary>
            [EnumMember(Value = "IMAGEMANAGER_VERIFICATION_FAILED")]
            IMAGEMANAGERVERIFICATIONFAILEDEnum = 210,

            /// <summary>
            /// Enum HELPREQUESTSUBMITTEDEnum for HELP_REQUEST_SUBMITTED
            /// </summary>
            [EnumMember(Value = "HELP_REQUEST_SUBMITTED")]
            HELPREQUESTSUBMITTEDEnum = 211,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTSCANSTARTEDEnum for SOFTWARE_PATCH_MANAGEMENT_SCAN_STARTED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT_SCAN_STARTED")]
            SOFTWAREPATCHMANAGEMENTSCANSTARTEDEnum = 212,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTSCANCOMPLETEDEnum for SOFTWARE_PATCH_MANAGEMENT_SCAN_COMPLETED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT_SCAN_COMPLETED")]
            SOFTWAREPATCHMANAGEMENTSCANCOMPLETEDEnum = 213,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTAPPLYPATCHSTARTEDEnum for SOFTWARE_PATCH_MANAGEMENT_APPLY_PATCH_STARTED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT_APPLY_PATCH_STARTED")]
            SOFTWAREPATCHMANAGEMENTAPPLYPATCHSTARTEDEnum = 214,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTAPPLYPATCHCOMPLETEDEnum for SOFTWARE_PATCH_MANAGEMENT_APPLY_PATCH_COMPLETED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT_APPLY_PATCH_COMPLETED")]
            SOFTWAREPATCHMANAGEMENTAPPLYPATCHCOMPLETEDEnum = 215,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTINSTALLEDEnum for SOFTWARE_PATCH_MANAGEMENT_INSTALLED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT_INSTALLED")]
            SOFTWAREPATCHMANAGEMENTINSTALLEDEnum = 216,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTINSTALLFAILEDEnum for SOFTWARE_PATCH_MANAGEMENT_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT_INSTALL_FAILED")]
            SOFTWAREPATCHMANAGEMENTINSTALLFAILEDEnum = 217,

            /// <summary>
            /// Enum SOFTWAREPATCHMANAGEMENTMESSAGEEnum for SOFTWARE_PATCH_MANAGEMENT_MESSAGE
            /// </summary>
            [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT_MESSAGE")]
            SOFTWAREPATCHMANAGEMENTMESSAGEEnum = 218,

            /// <summary>
            /// Enum CLOUDBERRYINSTALLEDEnum for CLOUDBERRY_INSTALLED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_INSTALLED")]
            CLOUDBERRYINSTALLEDEnum = 219,

            /// <summary>
            /// Enum CLOUDBERRYINSTALLFAILEDEnum for CLOUDBERRY_INSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_INSTALL_FAILED")]
            CLOUDBERRYINSTALLFAILEDEnum = 220,

            /// <summary>
            /// Enum CLOUDBERRYUNINSTALLEDEnum for CLOUDBERRY_UNINSTALLED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_UNINSTALLED")]
            CLOUDBERRYUNINSTALLEDEnum = 221,

            /// <summary>
            /// Enum CLOUDBERRYUNINSTALLFAILEDEnum for CLOUDBERRY_UNINSTALL_FAILED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_UNINSTALL_FAILED")]
            CLOUDBERRYUNINSTALLFAILEDEnum = 222,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPPLANCREATEDEnum for CLOUDBERRY_BACKUPPLAN_CREATED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPPLAN_CREATED")]
            CLOUDBERRYBACKUPPLANCREATEDEnum = 223,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPPLANEDITEDEnum for CLOUDBERRY_BACKUPPLAN_EDITED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPPLAN_EDITED")]
            CLOUDBERRYBACKUPPLANEDITEDEnum = 224,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPPLANDELETEDEnum for CLOUDBERRY_BACKUPPLAN_DELETED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPPLAN_DELETED")]
            CLOUDBERRYBACKUPPLANDELETEDEnum = 225,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPPLANCREATIONFAILEDEnum for CLOUDBERRY_BACKUPPLAN_CREATION_FAILED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPPLAN_CREATION_FAILED")]
            CLOUDBERRYBACKUPPLANCREATIONFAILEDEnum = 226,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPJOBSTARTEDEnum for CLOUDBERRY_BACKUPJOB_STARTED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPJOB_STARTED")]
            CLOUDBERRYBACKUPJOBSTARTEDEnum = 227,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPJOBSUCCEEDEDEnum for CLOUDBERRY_BACKUPJOB_SUCCEEDED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPJOB_SUCCEEDED")]
            CLOUDBERRYBACKUPJOBSUCCEEDEDEnum = 228,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPJOBFAILEDEnum for CLOUDBERRY_BACKUPJOB_FAILED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPJOB_FAILED")]
            CLOUDBERRYBACKUPJOBFAILEDEnum = 229,

            /// <summary>
            /// Enum CLOUDBERRYBACKUPJOBCOMPLETEDWITHWARNINGEnum for CLOUDBERRY_BACKUPJOB_COMPLETED_WITH_WARNING
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_BACKUPJOB_COMPLETED_WITH_WARNING")]
            CLOUDBERRYBACKUPJOBCOMPLETEDWITHWARNINGEnum = 230,

            /// <summary>
            /// Enum CLOUDBERRYUSERCREATEDEnum for CLOUDBERRY_USER_CREATED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_USER_CREATED")]
            CLOUDBERRYUSERCREATEDEnum = 231,

            /// <summary>
            /// Enum CLOUDBERRYNETWORKCREDENTIALCREATEDEnum for CLOUDBERRY_NETWORK_CREDENTIAL_CREATED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_NETWORK_CREDENTIAL_CREATED")]
            CLOUDBERRYNETWORKCREDENTIALCREATEDEnum = 232,

            /// <summary>
            /// Enum CLOUDBERRYNETWORKCREDENTIALCREATIONFAILEDEnum for CLOUDBERRY_NETWORK_CREDENTIAL_CREATION_FAILED
            /// </summary>
            [EnumMember(Value = "CLOUDBERRY_NETWORK_CREDENTIAL_CREATION_FAILED")]
            CLOUDBERRYNETWORKCREDENTIALCREATIONFAILEDEnum = 233,

            /// <summary>
            /// Enum RDPCONNECTIONINITIATEDEnum for RDP_CONNECTION_INITIATED
            /// </summary>
            [EnumMember(Value = "RDP_CONNECTION_INITIATED")]
            RDPCONNECTIONINITIATEDEnum = 234,

            /// <summary>
            /// Enum RDPCONNECTIONESTABLISHEDEnum for RDP_CONNECTION_ESTABLISHED
            /// </summary>
            [EnumMember(Value = "RDP_CONNECTION_ESTABLISHED")]
            RDPCONNECTIONESTABLISHEDEnum = 235,

            /// <summary>
            /// Enum RDPCONNECTIONTERMINATEDEnum for RDP_CONNECTION_TERMINATED
            /// </summary>
            [EnumMember(Value = "RDP_CONNECTION_TERMINATED")]
            RDPCONNECTIONTERMINATEDEnum = 236,

            /// <summary>
            /// Enum RDPAUTOPROVISIONEnum for RDP_AUTO_PROVISION
            /// </summary>
            [EnumMember(Value = "RDP_AUTO_PROVISION")]
            RDPAUTOPROVISIONEnum = 237,

            /// <summary>
            /// Enum NCSESSIONREQUESTEDEnum for NC_SESSION_REQUESTED
            /// </summary>
            [EnumMember(Value = "NC_SESSION_REQUESTED")]
            NCSESSIONREQUESTEDEnum = 238,

            /// <summary>
            /// Enum NCSESSIONSTARTEDEnum for NC_SESSION_STARTED
            /// </summary>
            [EnumMember(Value = "NC_SESSION_STARTED")]
            NCSESSIONSTARTEDEnum = 239,

            /// <summary>
            /// Enum NCSESSIONTERMINATEDEnum for NC_SESSION_TERMINATED
            /// </summary>
            [EnumMember(Value = "NC_SESSION_TERMINATED")]
            NCSESSIONTERMINATEDEnum = 240,

            /// <summary>
            /// Enum NCSESSIONSESSIONTERMINATIONREQUESTEDEnum for NC_SESSION_SESSION_TERMINATION_REQUESTED
            /// </summary>
            [EnumMember(Value = "NC_SESSION_SESSION_TERMINATION_REQUESTED")]
            NCSESSIONSESSIONTERMINATIONREQUESTEDEnum = 241,

            /// <summary>
            /// Enum SCHEDULEDTASKCREATEDEnum for SCHEDULED_TASK_CREATED
            /// </summary>
            [EnumMember(Value = "SCHEDULED_TASK_CREATED")]
            SCHEDULEDTASKCREATEDEnum = 242,

            /// <summary>
            /// Enum SCHEDULEDTASKUPDATEDEnum for SCHEDULED_TASK_UPDATED
            /// </summary>
            [EnumMember(Value = "SCHEDULED_TASK_UPDATED")]
            SCHEDULEDTASKUPDATEDEnum = 243,

            /// <summary>
            /// Enum SCHEDULEDTASKDELETEDEnum for SCHEDULED_TASK_DELETED
            /// </summary>
            [EnumMember(Value = "SCHEDULED_TASK_DELETED")]
            SCHEDULEDTASKDELETEDEnum = 244,

            /// <summary>
            /// Enum SCRIPTCREATEDEnum for SCRIPT_CREATED
            /// </summary>
            [EnumMember(Value = "SCRIPT_CREATED")]
            SCRIPTCREATEDEnum = 245,

            /// <summary>
            /// Enum SCRIPTUPDATEDEnum for SCRIPT_UPDATED
            /// </summary>
            [EnumMember(Value = "SCRIPT_UPDATED")]
            SCRIPTUPDATEDEnum = 246,

            /// <summary>
            /// Enum SCRIPTDELETEDEnum for SCRIPT_DELETED
            /// </summary>
            [EnumMember(Value = "SCRIPT_DELETED")]
            SCRIPTDELETEDEnum = 247,

            /// <summary>
            /// Enum SECURITYCREDENTIALACCESSGRANTEDEnum for SECURITY_CREDENTIAL_ACCESS_GRANTED
            /// </summary>
            [EnumMember(Value = "SECURITY_CREDENTIAL_ACCESS_GRANTED")]
            SECURITYCREDENTIALACCESSGRANTEDEnum = 248,

            /// <summary>
            /// Enum SECURITYCREDENTIALACCESSDENIEDEnum for SECURITY_CREDENTIAL_ACCESS_DENIED
            /// </summary>
            [EnumMember(Value = "SECURITY_CREDENTIAL_ACCESS_DENIED")]
            SECURITYCREDENTIALACCESSDENIEDEnum = 249,

            /// <summary>
            /// Enum REJECTEDNODEDELETEDEnum for REJECTED_NODE_DELETED
            /// </summary>
            [EnumMember(Value = "REJECTED_NODE_DELETED")]
            REJECTEDNODEDELETEDEnum = 250,

            /// <summary>
            /// Enum MOBILEDEVICEUNREGISTEREDEnum for MOBILE_DEVICE_UNREGISTERED
            /// </summary>
            [EnumMember(Value = "MOBILE_DEVICE_UNREGISTERED")]
            MOBILEDEVICEUNREGISTEREDEnum = 251,

            /// <summary>
            /// Enum REMOTETOOLSUPLOADFILEINITIATEDEnum for REMOTE_TOOLS_UPLOAD_FILE_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_UPLOAD_FILE_INITIATED")]
            REMOTETOOLSUPLOADFILEINITIATEDEnum = 252,

            /// <summary>
            /// Enum REMOTETOOLSDOWNLOADFILEINITIATEDEnum for REMOTE_TOOLS_DOWNLOAD_FILE_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DOWNLOAD_FILE_INITIATED")]
            REMOTETOOLSDOWNLOADFILEINITIATEDEnum = 253,

            /// <summary>
            /// Enum REMOTETOOLSCREATEDIRECTORYINITIATEDEnum for REMOTE_TOOLS_CREATE_DIRECTORY_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_CREATE_DIRECTORY_INITIATED")]
            REMOTETOOLSCREATEDIRECTORYINITIATEDEnum = 254,

            /// <summary>
            /// Enum REMOTETOOLSRENAMEFILEINITIATEDEnum for REMOTE_TOOLS_RENAME_FILE_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_RENAME_FILE_INITIATED")]
            REMOTETOOLSRENAMEFILEINITIATEDEnum = 255,

            /// <summary>
            /// Enum REMOTETOOLSDELETEFILEINITIATEDEnum for REMOTE_TOOLS_DELETE_FILE_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DELETE_FILE_INITIATED")]
            REMOTETOOLSDELETEFILEINITIATEDEnum = 256,

            /// <summary>
            /// Enum REMOTETOOLSMODIFYOBJECTSUCCESSEnum for REMOTE_TOOLS_MODIFY_OBJECT_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_MODIFY_OBJECT_SUCCESS")]
            REMOTETOOLSMODIFYOBJECTSUCCESSEnum = 257,

            /// <summary>
            /// Enum REMOTETOOLSMODIFYOBJECTFAILEDEnum for REMOTE_TOOLS_MODIFY_OBJECT_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_MODIFY_OBJECT_FAILED")]
            REMOTETOOLSMODIFYOBJECTFAILEDEnum = 258,

            /// <summary>
            /// Enum REMOTETOOLSCOPYOBJECTSUCCESSEnum for REMOTE_TOOLS_COPY_OBJECT_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_COPY_OBJECT_SUCCESS")]
            REMOTETOOLSCOPYOBJECTSUCCESSEnum = 259,

            /// <summary>
            /// Enum REMOTETOOLSCOPYOBJECTFAILEDEnum for REMOTE_TOOLS_COPY_OBJECT_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_COPY_OBJECT_FAILED")]
            REMOTETOOLSCOPYOBJECTFAILEDEnum = 260,

            /// <summary>
            /// Enum REMOTETOOLSMOVEOBJECTSUCCESSEnum for REMOTE_TOOLS_MOVE_OBJECT_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_MOVE_OBJECT_SUCCESS")]
            REMOTETOOLSMOVEOBJECTSUCCESSEnum = 261,

            /// <summary>
            /// Enum REMOTETOOLSMOVEOBJECTFAILEDEnum for REMOTE_TOOLS_MOVE_OBJECT_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_MOVE_OBJECT_FAILED")]
            REMOTETOOLSMOVEOBJECTFAILEDEnum = 262,

            /// <summary>
            /// Enum REMOTETOOLSDELETEOBJECTSUCCESSEnum for REMOTE_TOOLS_DELETE_OBJECT_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DELETE_OBJECT_SUCCESS")]
            REMOTETOOLSDELETEOBJECTSUCCESSEnum = 263,

            /// <summary>
            /// Enum REMOTETOOLSDELETEOBJECTFAILEDEnum for REMOTE_TOOLS_DELETE_OBJECT_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DELETE_OBJECT_FAILED")]
            REMOTETOOLSDELETEOBJECTFAILEDEnum = 264,

            /// <summary>
            /// Enum REMOTETOOLSCREATEDIRECTORYSUCCESSEnum for REMOTE_TOOLS_CREATE_DIRECTORY_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_CREATE_DIRECTORY_SUCCESS")]
            REMOTETOOLSCREATEDIRECTORYSUCCESSEnum = 265,

            /// <summary>
            /// Enum REMOTETOOLSCREATEDIRECTORYFAILEDEnum for REMOTE_TOOLS_CREATE_DIRECTORY_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_CREATE_DIRECTORY_FAILED")]
            REMOTETOOLSCREATEDIRECTORYFAILEDEnum = 266,

            /// <summary>
            /// Enum REMOTETOOLSFILETRANSFERSUCCESSEnum for REMOTE_TOOLS_FILE_TRANSFER_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_FILE_TRANSFER_SUCCESS")]
            REMOTETOOLSFILETRANSFERSUCCESSEnum = 267,

            /// <summary>
            /// Enum REMOTETOOLSFILETRANSFERFAILEDEnum for REMOTE_TOOLS_FILE_TRANSFER_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_FILE_TRANSFER_FAILED")]
            REMOTETOOLSFILETRANSFERFAILEDEnum = 268,

            /// <summary>
            /// Enum REMOTETOOLSSERVICECONTROLINITIATEDEnum for REMOTE_TOOLS_SERVICE_CONTROL_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_SERVICE_CONTROL_INITIATED")]
            REMOTETOOLSSERVICECONTROLINITIATEDEnum = 269,

            /// <summary>
            /// Enum REMOTETOOLSSTARTSERVICESUCCESSEnum for REMOTE_TOOLS_START_SERVICE_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_START_SERVICE_SUCCESS")]
            REMOTETOOLSSTARTSERVICESUCCESSEnum = 270,

            /// <summary>
            /// Enum REMOTETOOLSSTARTSERVICEFAILEDEnum for REMOTE_TOOLS_START_SERVICE_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_START_SERVICE_FAILED")]
            REMOTETOOLSSTARTSERVICEFAILEDEnum = 271,

            /// <summary>
            /// Enum REMOTETOOLSSTOPSERVICESUCCESSEnum for REMOTE_TOOLS_STOP_SERVICE_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_STOP_SERVICE_SUCCESS")]
            REMOTETOOLSSTOPSERVICESUCCESSEnum = 272,

            /// <summary>
            /// Enum REMOTETOOLSSTOPSERVICEFAILEDEnum for REMOTE_TOOLS_STOP_SERVICE_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_STOP_SERVICE_FAILED")]
            REMOTETOOLSSTOPSERVICEFAILEDEnum = 273,

            /// <summary>
            /// Enum REMOTETOOLSRESTARTSERVICESUCCESSEnum for REMOTE_TOOLS_RESTART_SERVICE_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_RESTART_SERVICE_SUCCESS")]
            REMOTETOOLSRESTARTSERVICESUCCESSEnum = 274,

            /// <summary>
            /// Enum REMOTETOOLSRESTARTSERVICEFAILEDEnum for REMOTE_TOOLS_RESTART_SERVICE_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_RESTART_SERVICE_FAILED")]
            REMOTETOOLSRESTARTSERVICEFAILEDEnum = 275,

            /// <summary>
            /// Enum REMOTETOOLSSTARTTYPECHANGESUCCESSEnum for REMOTE_TOOLS_START_TYPE_CHANGE_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_START_TYPE_CHANGE_SUCCESS")]
            REMOTETOOLSSTARTTYPECHANGESUCCESSEnum = 276,

            /// <summary>
            /// Enum REMOTETOOLSSTARTTYPECHANGEFAILEDEnum for REMOTE_TOOLS_START_TYPE_CHANGE_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_START_TYPE_CHANGE_FAILED")]
            REMOTETOOLSSTARTTYPECHANGEFAILEDEnum = 277,

            /// <summary>
            /// Enum REMOTETOOLSPROCESSCONTROLINITIATEDEnum for REMOTE_TOOLS_PROCESS_CONTROL_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_PROCESS_CONTROL_INITIATED")]
            REMOTETOOLSPROCESSCONTROLINITIATEDEnum = 278,

            /// <summary>
            /// Enum REMOTETOOLSSETPROCESSPRIORITYSUCESSEnum for REMOTE_TOOLS_SET_PROCESS_PRIORITY_SUCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_SET_PROCESS_PRIORITY_SUCESS")]
            REMOTETOOLSSETPROCESSPRIORITYSUCESSEnum = 279,

            /// <summary>
            /// Enum REMOTETOOLSSETPROCESSPRIORITYFAILEDEnum for REMOTE_TOOLS_SET_PROCESS_PRIORITY_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_SET_PROCESS_PRIORITY_FAILED")]
            REMOTETOOLSSETPROCESSPRIORITYFAILEDEnum = 280,

            /// <summary>
            /// Enum REMOTETOOLSTERMINATEPROCESSSUCCESSEnum for REMOTE_TOOLS_TERMINATE_PROCESS_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_TERMINATE_PROCESS_SUCCESS")]
            REMOTETOOLSTERMINATEPROCESSSUCCESSEnum = 281,

            /// <summary>
            /// Enum REMOTETOOLSTERMINATEPROCESSFAILEDEnum for REMOTE_TOOLS_TERMINATE_PROCESS_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_TERMINATE_PROCESS_FAILED")]
            REMOTETOOLSTERMINATEPROCESSFAILEDEnum = 282,

            /// <summary>
            /// Enum REMOTETOOLSTERMINATEPROCESSTREESUCCESSEnum for REMOTE_TOOLS_TERMINATE_PROCESS_TREE_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_TERMINATE_PROCESS_TREE_SUCCESS")]
            REMOTETOOLSTERMINATEPROCESSTREESUCCESSEnum = 283,

            /// <summary>
            /// Enum REMOTETOOLSTERMINATEPROCESSTREEFAILEDEnum for REMOTE_TOOLS_TERMINATE_PROCESS_TREE_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_TERMINATE_PROCESS_TREE_FAILED")]
            REMOTETOOLSTERMINATEPROCESSTREEFAILEDEnum = 284,

            /// <summary>
            /// Enum REMOTETOOLSREGISTRYCONTROLINITIATEDEnum for REMOTE_TOOLS_REGISTRY_CONTROL_INITIATED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_REGISTRY_CONTROL_INITIATED")]
            REMOTETOOLSREGISTRYCONTROLINITIATEDEnum = 285,

            /// <summary>
            /// Enum REMOTETOOLSCREATEKEYSUCCESSEnum for REMOTE_TOOLS_CREATE_KEY_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_CREATE_KEY_SUCCESS")]
            REMOTETOOLSCREATEKEYSUCCESSEnum = 286,

            /// <summary>
            /// Enum REMOTETOOLSCREATEKEYFAILEDEnum for REMOTE_TOOLS_CREATE_KEY_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_CREATE_KEY_FAILED")]
            REMOTETOOLSCREATEKEYFAILEDEnum = 287,

            /// <summary>
            /// Enum REMOTETOOLSRENAMEKEYSUCCESSEnum for REMOTE_TOOLS_RENAME_KEY_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_RENAME_KEY_SUCCESS")]
            REMOTETOOLSRENAMEKEYSUCCESSEnum = 288,

            /// <summary>
            /// Enum REMOTETOOLSRENAMEKEYFAILEDEnum for REMOTE_TOOLS_RENAME_KEY_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_RENAME_KEY_FAILED")]
            REMOTETOOLSRENAMEKEYFAILEDEnum = 289,

            /// <summary>
            /// Enum REMOTETOOLSDELETEKEYSUCCESSEnum for REMOTE_TOOLS_DELETE_KEY_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DELETE_KEY_SUCCESS")]
            REMOTETOOLSDELETEKEYSUCCESSEnum = 290,

            /// <summary>
            /// Enum REMOTETOOLSDELETEKEYFAILEDEnum for REMOTE_TOOLS_DELETE_KEY_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DELETE_KEY_FAILED")]
            REMOTETOOLSDELETEKEYFAILEDEnum = 291,

            /// <summary>
            /// Enum REMOTETOOLSCREATEPARAMETERSUCCESSEnum for REMOTE_TOOLS_CREATE_PARAMETER_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_CREATE_PARAMETER_SUCCESS")]
            REMOTETOOLSCREATEPARAMETERSUCCESSEnum = 292,

            /// <summary>
            /// Enum REMOTETOOLSCREATEPARAMETERFAILEDEnum for REMOTE_TOOLS_CREATE_PARAMETER_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_CREATE_PARAMETER_FAILED")]
            REMOTETOOLSCREATEPARAMETERFAILEDEnum = 293,

            /// <summary>
            /// Enum REMOTETOOLSRENAMEPARAMETERSUCCESSEnum for REMOTE_TOOLS_RENAME_PARAMETER_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_RENAME_PARAMETER_SUCCESS")]
            REMOTETOOLSRENAMEPARAMETERSUCCESSEnum = 294,

            /// <summary>
            /// Enum REMOTETOOLSRENAMEPARAMETERFAILEDEnum for REMOTE_TOOLS_RENAME_PARAMETER_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_RENAME_PARAMETER_FAILED")]
            REMOTETOOLSRENAMEPARAMETERFAILEDEnum = 295,

            /// <summary>
            /// Enum REMOTETOOLSDELETEPARAMETERSUCCESSEnum for REMOTE_TOOLS_DELETE_PARAMETER_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DELETE_PARAMETER_SUCCESS")]
            REMOTETOOLSDELETEPARAMETERSUCCESSEnum = 296,

            /// <summary>
            /// Enum REMOTETOOLSDELETEPARAMETERFAILEDEnum for REMOTE_TOOLS_DELETE_PARAMETER_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_DELETE_PARAMETER_FAILED")]
            REMOTETOOLSDELETEPARAMETERFAILEDEnum = 297,

            /// <summary>
            /// Enum REMOTETOOLSMODIFYPARAMETERSUCCESSEnum for REMOTE_TOOLS_MODIFY_PARAMETER_SUCCESS
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_MODIFY_PARAMETER_SUCCESS")]
            REMOTETOOLSMODIFYPARAMETERSUCCESSEnum = 298,

            /// <summary>
            /// Enum REMOTETOOLSMODIFYPARAMETERFAILEDEnum for REMOTE_TOOLS_MODIFY_PARAMETER_FAILED
            /// </summary>
            [EnumMember(Value = "REMOTE_TOOLS_MODIFY_PARAMETER_FAILED")]
            REMOTETOOLSMODIFYPARAMETERFAILEDEnum = 299,

            /// <summary>
            /// Enum APIACCESSGRANTEDEnum for API_ACCESS_GRANTED
            /// </summary>
            [EnumMember(Value = "API_ACCESS_GRANTED")]
            APIACCESSGRANTEDEnum = 300,

            /// <summary>
            /// Enum APIACCESSDENIEDEnum for API_ACCESS_DENIED
            /// </summary>
            [EnumMember(Value = "API_ACCESS_DENIED")]
            APIACCESSDENIEDEnum = 301,

            /// <summary>
            /// Enum APIWEBHOOKCONFIGURATIONUPDATEDEnum for API_WEBHOOK_CONFIGURATION_UPDATED
            /// </summary>
            [EnumMember(Value = "API_WEBHOOK_CONFIGURATION_UPDATED")]
            APIWEBHOOKCONFIGURATIONUPDATEDEnum = 302,

            /// <summary>
            /// Enum APIACCESSREVOKEDEnum for API_ACCESS_REVOKED
            /// </summary>
            [EnumMember(Value = "API_ACCESS_REVOKED")]
            APIACCESSREVOKEDEnum = 303,

            /// <summary>
            /// Enum UNKNOWNEnum for UNKNOWN
            /// </summary>
            [EnumMember(Value = "UNKNOWN")]
            UNKNOWNEnum = 304
        }

        /// <summary>
        /// Activity status code
        /// </summary>
        /// <value>Activity status code</value>
        [DataMember(Name = "statusCode", EmitDefaultValue = false)]
        public StatusCodeEnum StatusCode { get; set; }

        /// <summary>
        /// Status description
        /// </summary>
        /// <value>Status description</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }


        /// <summary>
        /// Activity result
        /// </summary>
        /// <value>Activity result</value>
        [TypeConverter(typeof(CustomEnumConverter<ActivityResultEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ActivityResultEnum
        {

            /// <summary>
            /// Enum SUCCESSEnum for SUCCESS
            /// </summary>
            [EnumMember(Value = "SUCCESS")]
            SUCCESSEnum = 1,

            /// <summary>
            /// Enum FAILUREEnum for FAILURE
            /// </summary>
            [EnumMember(Value = "FAILURE")]
            FAILUREEnum = 2,

            /// <summary>
            /// Enum UNSUPPORTEDEnum for UNSUPPORTED
            /// </summary>
            [EnumMember(Value = "UNSUPPORTED")]
            UNSUPPORTEDEnum = 3,

            /// <summary>
            /// Enum UNCOMPLETEDEnum for UNCOMPLETED
            /// </summary>
            [EnumMember(Value = "UNCOMPLETED")]
            UNCOMPLETEDEnum = 4
        }

        /// <summary>
        /// Activity result
        /// </summary>
        /// <value>Activity result</value>
        [DataMember(Name = "activityResult", EmitDefaultValue = false)]
        public ActivityResultEnum ActivityResult { get; set; }

        /// <summary>
        /// Source configuration/policy element reference
        /// </summary>
        /// <value>Source configuration/policy element reference</value>
        [DataMember(Name = "sourceConfigUid", EmitDefaultValue = false)]
        public Guid SourceConfigUid { get; set; }

        /// <summary>
        /// Source configuration/policy element name
        /// </summary>
        /// <value>Source configuration/policy element name</value>
        [DataMember(Name = "sourceName", EmitDefaultValue = false)]
        public string SourceName { get; set; }

        /// <summary>
        /// Activity subject
        /// </summary>
        /// <value>Activity subject</value>
        [DataMember(Name = "subject", EmitDefaultValue = false)]
        public string Subject { get; set; }

        /// <summary>
        /// User identifier
        /// </summary>
        /// <value>User identifier</value>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public int UserId { get; set; }

        /// <summary>
        /// Activity message
        /// </summary>
        /// <value>Activity message</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Activity type description
        /// </summary>
        /// <value>Activity type description</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public Dictionary<string, Object> Data { get; set; }

        /// <summary>
        /// Gets or Sets Device
        /// </summary>
        [DataMember(Name = "device", EmitDefaultValue = false)]
        public NodeWithDetailedReferences Device { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DetailedActivity {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ActivityTime: ").Append(ActivityTime).Append("\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  SeriesUid: ").Append(SeriesUid).Append("\n");
            sb.Append("  ActivityType: ").Append(ActivityType).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ActivityResult: ").Append(ActivityResult).Append("\n");
            sb.Append("  SourceConfigUid: ").Append(SourceConfigUid).Append("\n");
            sb.Append("  SourceName: ").Append(SourceName).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DetailedActivity)obj);
        }

        /// <summary>
        /// Returns true if DetailedActivity instances are equal
        /// </summary>
        /// <param name="other">Instance of DetailedActivity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DetailedActivity other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||

                    Id.Equals(other.Id)
                ) &&
                (
                    ActivityTime == other.ActivityTime ||

                    ActivityTime.Equals(other.ActivityTime)
                ) &&
                (
                    DeviceId == other.DeviceId ||

                    DeviceId.Equals(other.DeviceId)
                ) &&
                (
                    Severity == other.Severity ||

                    Severity.Equals(other.Severity)
                ) &&
                (
                    Priority == other.Priority ||

                    Priority.Equals(other.Priority)
                ) &&
                (
                    SeriesUid == other.SeriesUid ||
                    SeriesUid != null &&
                    SeriesUid.Equals(other.SeriesUid)
                ) &&
                (
                    ActivityType == other.ActivityType ||

                    ActivityType.Equals(other.ActivityType)
                ) &&
                (
                    StatusCode == other.StatusCode ||

                    StatusCode.Equals(other.StatusCode)
                ) &&
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) &&
                (
                    ActivityResult == other.ActivityResult ||

                    ActivityResult.Equals(other.ActivityResult)
                ) &&
                (
                    SourceConfigUid == other.SourceConfigUid ||
                    SourceConfigUid != null &&
                    SourceConfigUid.Equals(other.SourceConfigUid)
                ) &&
                (
                    SourceName == other.SourceName ||
                    SourceName != null &&
                    SourceName.Equals(other.SourceName)
                ) &&
                (
                    Subject == other.Subject ||
                    Subject != null &&
                    Subject.Equals(other.Subject)
                ) &&
                (
                    UserId == other.UserId ||

                    UserId.Equals(other.UserId)
                ) &&
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) &&
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) &&
                (
                    Data == other.Data ||
                    Data != null &&
                    other.Data != null &&
                    Data.SequenceEqual(other.Data)
                ) &&
                (
                    Device == other.Device ||
                    Device != null &&
                    Device.Equals(other.Device)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + Id.GetHashCode();

                hashCode = hashCode * 59 + ActivityTime.GetHashCode();

                hashCode = hashCode * 59 + DeviceId.GetHashCode();

                hashCode = hashCode * 59 + Severity.GetHashCode();

                hashCode = hashCode * 59 + Priority.GetHashCode();
                if (SeriesUid != null)
                    hashCode = hashCode * 59 + SeriesUid.GetHashCode();

                hashCode = hashCode * 59 + ActivityType.GetHashCode();

                hashCode = hashCode * 59 + StatusCode.GetHashCode();
                if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();

                hashCode = hashCode * 59 + ActivityResult.GetHashCode();
                if (SourceConfigUid != null)
                    hashCode = hashCode * 59 + SourceConfigUid.GetHashCode();
                if (SourceName != null)
                    hashCode = hashCode * 59 + SourceName.GetHashCode();
                if (Subject != null)
                    hashCode = hashCode * 59 + Subject.GetHashCode();

                hashCode = hashCode * 59 + UserId.GetHashCode();
                if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Data != null)
                    hashCode = hashCode * 59 + Data.GetHashCode();
                if (Device != null)
                    hashCode = hashCode * 59 + Device.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(DetailedActivity left, DetailedActivity right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DetailedActivity left, DetailedActivity right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
