# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
COPY ./bin/Release/netcoreapp3.1/publish/ App/

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:3.1
COPY ./bin/Release/netcoreapp3.1/publish/ App/
#COPY --from=build-env /app/out .
WORKDIR /App
ENTRYPOINT ["dotnet", "ProactiveBot.dll"]